export const ACT_VALUES_MASTER = [
    "Aandacht", "Eerlijkheid", "Macht", "Stabiliteit",
    "Aanpassen", "Empathie", "Milieubewust", "Structuur",
    "Acceptatie", "Enthousiasme", "Mindful", "Tactvol",
    "Afwisseling", "Erkenning", "Moed", "Tevredenheid",
    "Altruïsme", "Excelleren", "Nauwkeurigheid", "Toewijding",
    "Ambitieus", "Familie", "Nederigheid", "Traditie",
    "Assertiviteit", "Flexibiliteit", "Nieuwsgierigheid", "Trouw",
    "Attent", "Gastvrijheid", "Nut", "Uitdaging",
    "Authenticiteit", "Geduld", "Ontspanning", "Veiligheid",
    "Autonomie", "Gelijkwaardigheid", "Ontwikkeling", "Verantwoordelijkheid",
    "Avontuurlijkheid", "Georganiseerd", "Openheid", "Verbeelding",
    "Balans", "Gezag", "Oprechtheid", "Verbinding",
    "Behulpzaamheid", "Gezelligheid", "Optimisme", "Verdraagzaamheid",
    "Bekwaamheid", "Gezondheid", "Originaliteit", "Vergeving",
    "Bemoedigend", "Groei", "Passie", "Vertrouwen",
    "Bescheidenheid", "Hoffelijkheid", "Plezier", "Verwondering",
    "Beschermen", "Hoop", "Plichtsgetrouw", "Vriendschap",
    "Betrokkenheid", "Hulpvaardigheid", "Praktisch", "Vrijgevigheid",
    "Betrouwbaarheid", "Humor", "Professionaliteit", "Vrijheid",
    "Bewustzijn", "Ijverig", "Rationaliteit", "Waardering",
    "Bijdragen", "Innovatief", "Rechtvaardigheid", "Warmte",
    "Comfort", "Integriteit", "Respect", "Wederkerig",
    "Compassie", "Intimiteit", "Roem", "Welvaart",
    "Compromis", "Inzet", "Romantiek", "Wijsheid ",
    "Creativiteit ", "Inzicht ", "Rust ", "Zelfbeheersing ",
    "Dankbaarheid ", "Kennis ", "Samenwerking ", "Zelfkennis ",
    "Discipline ", "Kracht ", "Schoonheid ", "Zelfwaardering ",
    "Dienstbaarheid ", "Kunst ", "Seksualiteit ", "Zinvolheid ",
    "Diepgang ", "Kwaliteit ", "Sociaal ", "Zorgzaamheid ",
    "Doelgerichtheid ", "Leiderschap ", "Solidariteit ",
    "Duurzaamheid ", "Liefde ", "Spanning ",
    "Eenvoud ", "Loyaliteit ", "Spiritualiteit",
];