export type CategoryType = "ZELF" | "VERBINDING" | "PRESTATIE" | "HARMONIE" | "DYNAMIEK";

export interface CategoryQuestion {
  id: number;
  text: string;
  cat: CategoryType;
}

export interface ValueQuestion {
  text: string;
  cat: CategoryType;
  value: string;
}

/**
 * FASE 1: De 20 categorie-vragen om de dominantie te bepalen
 */
export const PHASE1_QUESTIONS: CategoryQuestion[] = [
  // ZELF
  { id: 1, text: "Hoe belangrijk vind je het om elke dag iets nieuws te leren of jezelf te ontwikkelen?", cat: "ZELF" },
  { id: 2, text: "In hoeverre streef je ernaar om in elke situatie volledig jezelf (authentiek) te kunnen zijn?", cat: "ZELF" },
  { id: 3, text: "Hoeveel waarde hecht je aan zelfreflectie en het begrijpen van je eigen drijfveren?", cat: "ZELF" },
  { id: 4, text: "Is het voor jou essentieel om autonoom te zijn en je eigen keuzes te maken zonder invloed van buitenaf?", cat: "ZELF" },
  // VERBINDING
  { id: 5, text: "Hoeveel voldoening haal je uit het helpen van anderen zonder daar iets voor terug te verwachten?", cat: "VERBINDING" },
  { id: 6, text: "Hoe belangrijk is het voor jou om diepe, betekenisvolle relaties te hebben in plaats van veel oppervlakkige contacten?", cat: "VERBINDING" },
  { id: 7, text: "In welke mate streef je naar harmonie en goede samenwerking binnen een groep of team?", cat: "VERBINDING" },
  { id: 8, text: "Hoe belangrijk vind je het om empathie en compassie te tonen naar mensen die het moeilijk hebben?", cat: "VERBINDING" },
  // PRESTATIE
  { id: 9, text: "Hoeveel waarde hecht je aan het behalen van concrete resultaten en het leveren van kwaliteit?", cat: "PRESTATIE" },
  { id: 10, text: "Is een duidelijke structuur en organisatie in je (werk)dag voor jou noodzakelijk om goed te functioneren?", cat: "PRESTATIE" },
  { id: 11, text: "Hoe belangrijk vind je het om verantwoordelijkheid te dragen voor grote projecten of beslissingen?", cat: "PRESTATIE" },
  { id: 12, text: "Streef je ernaar om uit te blinken in wat je doet en erkenning te krijgen voor je vakmanschap?", cat: "PRESTATIE" },
  // HARMONIE
  { id: 13, text: "Hoe belangrijk is een gezonde balans tussen je werk en je privéleven voor je geluksgevoel?", cat: "HARMONIE" },
  { id: 14, text: "Zoek je bewust naar rust en stabiliteit in je omgeving om stress te voorkomen?", cat: "HARMONIE" },
  { id: 15, text: "Hoeveel waarde hecht je aan een duurzame levensstijl en zorg voor het milieu?", cat: "HARMONIE" },
  { id: 16, text: "Is een gevoel van innerlijke tevredenheid voor jou belangrijker dan het najagen van status of succes?", cat: "HARMONIE" },
  // DYNAMIEK
  { id: 17, text: "Hoezeer geniet je van onverwachte situaties en avontuurlijke uitdagingen?", cat: "DYNAMIEK" },
  { id: 18, text: "Hoe belangrijk vind je het om volledige vrijheid te hebben in hoe je je tijd indeelt?", cat: "DYNAMIEK" },
  { id: 19, text: "Zoek je in je leven vaak naar afwisseling en nieuwe ervaringen om verveling te voorkomen?", cat: "DYNAMIEK" },
  { id: 20, text: "Ben je bereid om risico's te nemen als dat leidt tot innovatie of persoonlijke vrijheid?", cat: "DYNAMIEK" },
];

/**
 * FASE 2: De 200 vragen voor specifieke waarden
 */
export const VALUE_QUESTIONS: ValueQuestion[] = [
  // --- CATEGORIE: ZELF ---
  { text: "Ben je altijd trouw aan je eigen karakter, ook onder groepsdruk?", cat: "ZELF", value: "Authenticiteit" },
  { text: "Neem je beslissingen liever zelfstandig zonder advies te vragen?", cat: "ZELF", value: "Autonomie" },
  { text: "Ben je je gedurende de dag bewust van je innerlijke dialoog?", cat: "ZELF", value: "Bewustzijn" },
  { text: "Heb je een sterke drang om iets nieuws te creëren (kunst, ideeën)?", cat: "ZELF", value: "Creativiteit" },
  { text: "Sta je dagelijks stil bij waar je dankbaar voor bent?", cat: "ZELF", value: "Dankbaarheid" },
  { text: "Vermijd je liever oppervlakkige gesprekken (small talk)?", cat: "ZELF", value: "Diepgang" },
  { text: "Kun je jezelf goed motiveren voor taken waar je geen zin in hebt?", cat: "ZELF", value: "Discipline" },
  { text: "Heb je duidelijke lange-termijn doelen voor je leven?", cat: "ZELF", value: "Doelgerichtheid" },
  { text: "Is 'stilstaan is achteruitgaan' op jou van toepassing?", cat: "ZELF", value: "Groei" },
  { text: "Krijg je vaak plotselinge, diepe ingevingen?", cat: "ZELF", value: "Inzicht" },
  { text: "Besteed je veel tijd aan het lezen van feitelijke informatie?", cat: "ZELF", value: "Kennis" },
  { text: "Voel je je mentaal krachtig genoeg om grote tegenslagen aan te kunnen?", cat: "ZELF", value: "Kracht" },
  { text: "Stap je vaak uit je comfortzone ondanks je angst?", cat: "ZELF", value: "Moed" },
  { text: "Wil je van alles precies weten hoe de vork in de steel zit?", cat: "ZELF", value: "Nieuwsgierigheid" },
  { text: "Investeer je structureel in persoonlijke training of cursussen?", cat: "ZELF", value: "Ontwikkeling" },
  { text: "Heb je een passie die je de tijd doet vergeten?", cat: "ZELF", value: "Passie" },
  { text: "Geef je nooit op als je ergens echt in gelooft?", cat: "ZELF", value: "Toewijding" },
  { text: "Dagdroom je vaak over nieuwe scenario's en mogelijkheden?", cat: "ZELF", value: "Verbeelding" },
  { text: "Heb je een basisvertrouwen dat het leven goed afloopt?", cat: "ZELF", value: "Vertrouwen" },
  { text: "Word je vaak om advies gevraagd vanwege je levenservaring?", cat: "ZELF", value: "Wijsheid" },
  { text: "Kun je je impulsen (zoals snoepen of boosheid) goed beheersen?", cat: "ZELF", value: "Zelfbeheersing" },
  { text: "Begrijp je waarom je op een bepaalde manier reageert?", cat: "ZELF", value: "Zelfkennis" },
  { text: "Ben je oprecht trots op wie je bent geworden?", cat: "ZELF", value: "Zelfwaardering" },
  { text: "Moet jouw werk of leven een diepere betekenis hebben?", cat: "ZELF", value: "Zinvolheid" },
  { text: "Durf je 'nee' te zeggen als iets niet bij je waarden past?", cat: "ZELF", value: "Authenticiteit" },
  { text: "Voel je je pas prettig als je financieel onafhankelijk bent?", cat: "ZELF", value: "Autonomie" },
  { text: "Ben je je bewust van je fysieke aanwezigheid in een ruimte?", cat: "ZELF", value: "Bewustzijn" },
  { text: "Is artistieke expressie een noodzaak voor jouw geluk?", cat: "ZELF", value: "Creativiteit" },
  { text: "Zie je elke fout als een waardevolle les?", cat: "ZELF", value: "Groei" },
  { text: "Geloof je onvoorwaardelijk in je eigen potentieel?", cat: "ZELF", value: "Zelfwaardering" },
  { text: "Kun je je aandacht langdurig op één complex probleem richten?", cat: "ZELF", value: "Diepgang" },
  { text: "Houd je je aan je eigen routine, ook als je moe bent?", cat: "ZELF", value: "Discipline" },
  { text: "Ben je bereid offers te brengen voor je uiteindelijke doel?", cat: "ZELF", value: "Toewijding" },
  { text: "Zoek je naar patronen in informatie die anderen niet zien?", cat: "ZELF", value: "Inzicht" },
  { text: "Ben je eerlijk naar jezelf over je eigen schaduwkanten?", cat: "ZELF", value: "Zelfkennis" },
  { text: "Is je zelfbeheersing groter dan die van de meeste mensen?", cat: "ZELF", value: "Zelfbeheersing" },
  { text: "Kun je genieten van stilte en alleen zijn met je gedachten?", cat: "ZELF", value: "Bewustzijn" },
  { text: "Durf je je kwetsbaar op te stellen om authentiek te zijn?", cat: "ZELF", value: "Authenticiteit" },
  { text: "Is wijsheid voor jou belangrijker dan slimheid?", cat: "ZELF", value: "Wijsheid" },
  { text: "Voelt je leven op dit moment betekenisvol aan?", cat: "ZELF", value: "Zinvolheid" },

  // --- CATEGORIE: VERBINDING ---
  { text: "Pas je je gedrag makkelijk aan de sfeer in een groep aan?", cat: "VERBINDING", value: "Aanpassen" },
  { text: "Laat je anderen in hun waarde, ook als ze falen?", cat: "VERBINDING", value: "Acceptatie" },
  { text: "Zet je het belang van een ander vaak boven je eigen belang?", cat: "VERBINDING", value: "Altruïsme" },
  { text: "Onthoud je kleine, persoonlijke details over anderen?", cat: "VERBINDING", value: "Attent" },
  { text: "Ben je de eerste die hulp aanbiedt als iemand het nodig heeft?", cat: "VERBINDING", value: "Behulpzaamheid" },
  { text: "Geef je anderen vaak complimenten om ze te steunen?", cat: "VERBINDING", value: "Bemoedigend" },
  { text: "Voel je je emotioneel verantwoordelijk voor je omgeving?", cat: "VERBINDING", value: "Betrokkenheid" },
  { text: "Kun je oprecht meevoelen met het leed van een ander?", cat: "VERBINDING", value: "Compassie" },
  { text: "Ben je bereid een middenweg te zoeken bij elk conflict?", cat: "VERBINDING", value: "Compromis" },
  { text: "Doe je graag iets voor de maatschappij zonder beloning?", cat: "VERBINDING", value: "Dienstbaarheid" },
  { text: "Begrijp je de emoties van anderen zonder woorden?", cat: "VERBINDING", value: "Empathie" },
  { text: "Is je huis een plek waar iedereen zich direct welkom voelt?", cat: "VERBINDING", value: "Gastvrijheid" },
  { text: "Behandel je iedereen gelijk, ongeacht status of rang?", cat: "VERBINDING", value: "Gelijkwaardigheid" },
  { text: "Houd je van avonden vol lachen en samenzijn?", cat: "VERBINDING", value: "Gezelligheid" },
  { text: "Vind je goede omgangsvormen en beleefdheid essentieel?", cat: "VERBINDING", value: "Hoffelijkheid" },
  { text: "Zoek je actief naar manieren om nuttig te zijn voor de ander?", cat: "VERBINDING", value: "Hulpvaardigheid" },
  { text: "Gebruik je humor om moeilijke situaties te verlichten?", cat: "VERBINDING", value: "Humor" },
  { text: "Hecht je veel waarde aan diepe emotionele nabijheid?", cat: "VERBINDING", value: "Intimiteit" },
  { text: "Laat je je dierbaren dagelijks merken dat je van ze houdt?", cat: "VERBINDING", value: "Liefde" },
  { text: "Blijf je je vrienden trouw, ook als ze een fout maken?", cat: "VERBINDING", value: "Loyaliteit" },
  { text: "Ben je een 'open boek' over je eigen innerlijke wereld?", cat: "VERBINDING", value: "Openheid" },
  { text: "Geniet je van romantische sferen en attente gebaren?", cat: "VERBINDING", value: "Romantiek" },
  { text: "Is het resultaat altijd beter als je het samen doet?", cat: "VERBINDING", value: "Samenwerking" },
  { text: "Is fysieke passie een onmisbaar deel van je relatie?", cat: "VERBINDING", value: "Seksualiteit" },
  { text: "Heb je veel sociaal contact nodig om energie te krijgen?", cat: "VERBINDING", value: "Sociaal" },
  { text: "Kom je op voor mensen die onrecht wordt aangedaan?", cat: "VERBINDING", value: "Solidariteit" },
  { text: "Weet je precies hoe je iets moet zeggen zonder te kwetsen?", cat: "VERBINDING", value: "Tactvol" },
  { text: "Ben je een rots in de branding voor je partner?", cat: "VERBINDING", value: "Trouw" },
  { text: "Voel je je verbonden met je familie of gemeenschap?", cat: "VERBINDING", value: "Verbinding" },
  { text: "Accepteer je dat mensen radicaal andere meningen hebben?", cat: "VERBINDING", value: "Verdraagzaamheid" },
  { text: "Laat je wrok snel varen nadat iemand zijn excuses aanbiedt?", cat: "VERBINDING", value: "Vergeving" },
  { text: "Investeer je veel tijd in het onderhouden van vriendschappen?", cat: "VERBINDING", value: "Vriendschap" },
  { text: "Laat je anderen vaak weten dat je ze waardeert?", cat: "VERBINDING", value: "Waardering" },
  { text: "Stralen jouw huis en persoonlijkheid warmte uit?", cat: "VERBINDING", value: "Warmte" },
  { text: "Verwacht je van anderen dezelfde inzet als jij geeft?", cat: "VERBINDING", value: "Wederkerig" },
  { text: "Zorg je graag voor mens, dier of natuur?", cat: "VERBINDING", value: "Zorgzaamheid" },
  { text: "Kun je goed luisteren zonder direct advies te geven?", cat: "VERBINDING", value: "Empathie" },
  { text: "Ben je bereid je eigen gelijk op te geven voor de vrede?", cat: "VERBINDING", value: "Compromis" },
  { text: "Deel je je succes graag met de mensen om je heen?", cat: "VERBINDING", value: "Samenwerking" },
  { text: "Voel je je snel verantwoordelijk voor de sfeer in een groep?", cat: "VERBINDING", value: "Verbinding" },

  // --- CATEGORIE: PRESTATIE ---
  { text: "Wil je de absolute top bereiken in wat je doet?", cat: "PRESTATIE", value: "Ambitieus" },
  { text: "Durf je voor je mening uit te komen in een lastige vergadering?", cat: "PRESTATIE", value: "Assertiviteit" },
  { text: "Ben je trots op je professionele vaardigheden?", cat: "PRESTATIE", value: "Bekwaamheid" },
  { text: "Laat je je resultaten liever voor zich spreken dan te pochen?", cat: "PRESTATIE", value: "Bescheidenheid" },
  { text: "Kom je je afspraken altijd na, wat er ook gebeurt?", cat: "PRESTATIE", value: "Betrouwbaarheid" },
  { text: "Wil je dat jouw werk een meetbare bijdrage levert?", cat: "PRESTATIE", value: "Bijdragen" },
  { text: "Kies je vaak voor de meest eenvoudige, sobere oplossing?", cat: "PRESTATIE", value: "Eenvoud" },
  { text: "Is de waarheid voor jou belangrijker dan 'aardig gevonden worden'?", cat: "PRESTATIE", value: "Eerlijkheid" },
  { text: "Leg je de lat voor jezelf altijd net iets hoger dan anderen?", cat: "PRESTATIE", value: "Excelleren" },
  { text: "Hebben al jouw digitale en fysieke mappen een logische structuur?", cat: "PRESTATIE", value: "Georganiseerd" },
  { text: "Heb je respect voor hiërarchie en leidinggevenden?", cat: "PRESTATIE", value: "Gezag" },
  { text: "Ben je een harde werker die pas stopt als het af is?", cat: "PRESTATIE", value: "Ijverig" },
  { text: "Zoek je altijd naar manieren om processen te versnellen?", cat: "PRESTATIE", value: "Innovatief" },
  { text: "Toon je 100% inzet bij elke taak, hoe klein ook?", cat: "PRESTATIE", value: "Inzet" },
  { text: "Is de kwaliteit van je werk je belangrijkste visitekaartje?", cat: "PRESTATIE", value: "Kwaliteit" },
  { text: "Neem je natuurlijk de leiding als er chaos ontstaat?", cat: "PRESTATIE", value: "Leiderschap" },
  { text: "Vind je het prettig om de controle te hebben over middelen?", cat: "PRESTATIE", value: "Macht" },
  { text: "Controleer je je werk altijd op de kleinste details?", cat: "PRESTATIE", value: "Nauwkeurigheid" },
  { text: "Moet alles wat je doet een direct praktisch nut hebben?", cat: "PRESTATIE", value: "Nut" },
  { text: "Voel je je moreel verplicht om je beloften na te komen?", cat: "PRESTATIE", value: "Plichtsgetrouw" },
  { text: "Ben je een 'doener' die niet blijft hangen in plannen?", cat: "PRESTATIE", value: "Praktisch" },
  { text: "Gedraag je je altijd zakelijk en deskundig op je werk?", cat: "PRESTATIE", value: "Professionaliteit" },
  { text: "Neem je beslissingen puur op basis van feiten en logica?", cat: "PRESTATIE", value: "Rationaliteit" },
  { text: "Vind je het essentieel dat iedereen krijgt wat hij verdient?", cat: "PRESTATIE", value: "Rechtvaardigheid" },
  { text: "Behandel je mensen met eerbied voor hun ervaring?", cat: "PRESTATIE", value: "Respect" },
  { text: "Is erkenning of roem een drijfveer voor je succes?", cat: "PRESTATIE", value: "Roem" },
  { text: "Is een vast contract en financiële zekerheid cruciaal voor je?", cat: "PRESTATIE", value: "Stabiliteit" },
  { text: "Heb heb je een hekel aan werken zonder duidelijk kader of plan?", cat: "PRESTATIE", value: "Structuur" },
  { text: "Neem je de schuld op je als je team een fout maakt?", cat: "PRESTATIE", value: "Verantwoordelijkheid" },
  { text: "Is het opbouwen van vermogen een belangrijk doel?", cat: "PRESTATIE", value: "Welvaart" },
  { text: "Werk je liever met een checklist dan uit de losse pols?", cat: "PRESTATIE", value: "Structuur" },
  { text: "Durf je mensen aan te spreken op hun verantwoordelijkheid?", cat: "PRESTATIE", value: "Assertiviteit" },
  { text: "Houd je van een sobere levensstijl zonder onnodige franje?", cat: "PRESTATIE", value: "Eenvoud" },
  { text: "Ben je bereid meer te doen dan wat er in je functieomschrijving staat?", cat: "PRESTATIE", value: "Inzet" },
  { text: "Wil je dat men jou ziet als een expert in je vak?", cat: "PRESTATIE", value: "Bekwaamheid" },
  { text: "Gebruik je data en cijfers om je punt te bewijzen?", cat: "PRESTATIE", value: "Rationaliteit" },
  { text: "Kun je goed omgaan met autoriteit boven je?", cat: "PRESTATIE", value: "Gezag" },
  { text: "Streef je naar een foutloze uitvoering van je taken?", cat: "PRESTATIE", value: "Excelleren" },
  { text: "Vind je dat discipline de basis is van elk succes?", cat: "PRESTATIE", value: "Discipline" },
  { text: "Ben je bereid je eigen belang op te offeren voor de organisatie?", cat: "PRESTATIE", value: "Plichtsgetrouw" },

  // --- CATEGORIE: HARMONIE ---
  { text: "Bewaak je de grens tussen werk en privé heel streng?", cat: "HARMONIE", value: "Balans" },
  { text: "Bescherm je instinctief mensen of dieren in nood?", cat: "HARMONIE", value: "Beschermen" },
  { text: "Geef je graag geld uit aan comfort en een fijn huis?", cat: "HARMONIE", value: "Comfort" },
  { text: "Denk je bij elke aankoop na over de milieu-impact?", cat: "HARMONIE", value: "Duurzaamheid" },
  { text: "Is jouw enthousiasme vaak aanstekelijk voor je omgeving?", cat: "HARMONIE", value: "Enthousiasme" },
  { text: "Kun je je plannen direct omgooien als de situatie verandert?", cat: "HARMONIE", value: "Flexibiliteit" },
  { text: "Kun je wachten op resultaat zonder onrustig te worden?", cat: "HARMONIE", value: "Geduld" },
  { text: "Is gezond eten en genoeg bewegen een dagelijkse prioriteit?", cat: "HARMONIE", value: "Gezondheid" },
  { text: "Blijf je geloven in een goede afloop, ook bij tegenslag?", cat: "HARMONIE", value: "Hoop" },
  { text: "Kan een kunstwerk of muziekstuk je tot tranen roeren?", cat: "HARMONIE", value: "Kunst" },
  { text: "Doe je actief aan afvalscheiding en energiebesparing?", cat: "HARMONIE", value: "Milieubewust" },
  { text: "Neem je elke dag tijd voor stilte of meditatie?", cat: "HARMONIE", value: "Ontspanning" },
  { text: "Bekijk je de wereld altijd vanuit een positieve hoek?", cat: "HARMONIE", value: "Optimisme" },
  { text: "Ben je altijd eerlijk over wat je echt voelt?", cat: "HARMONIE", value: "Oprechtheid" },
  { text: "Is plezier maken voor jou belangrijker dan carrière maken?", cat: "HARMONIE", value: "Plezier" },
  { text: "Heb je een grote behoefte aan een stille, prikkelarme omgeving?", cat: "HARMONIE", value: "Rust" },
  { text: "Kun je intens genieten van een mooi landschap?", cat: "HARMONIE", value: "Schoonheid" },
  { text: "Ben je diep gelukkig met wat je nu hebt?", cat: "HARMONIE", value: "Tevredenheid" },
  { text: "Houd je vast aan familiegebruiken en feestdagen?", cat: "HARMONIE", value: "Traditie" },
  { text: "Is een veilig en stabiel fundament je hoogste prioriteit?", cat: "HARMONIE", value: "Veiligheid" },
  { text: "Kijk je nog steeds met kinderlijke verbazing naar de wereld?", cat: "HARMONIE", value: "Verwondering" },
  { text: "Deel je makkelijk je tijd of geld met goede doelen?", cat: "HARMONIE", value: "Vrijgevigheid" },
  { text: "Vermijd je ruzies om de sfeer goed te houden?", cat: "HARMONIE", value: "Balans" },
  { text: "Voel je je verbonden met de seizoenen en de natuur?", cat: "HARMONIE", value: "Milieubewust" },
  { text: "Is je geweten je belangrijkste raadgever?", cat: "HARMONIE", value: "Oprechtheid" },
  { text: "Kun je goed omgaan met vertragingen in het verkeer of leven?", cat: "HARMONIE", value: "Geduld" },
  { text: "Is jouw lach vaak in een kamer te horen?", cat: "HARMONIE", value: "Optimisme" },
  { text: "Voel je je verantwoordelijk voor de toekomst van de planeet?", cat: "HARMONIE", value: "Duurzaamheid" },
  { text: "Is een gezellige sfeer voor jou belangrijker dan een schoon huis?", cat: "HARMONIE", value: "Gezelligheid" },
  { text: "Ben je een optimist in hart en nieren?", cat: "HARMONIE", value: "Optimisme" },
  { text: "Zoek je vaak de balans tussen je hoofd en je hart?", cat: "HARMONIE", value: "Balans" },
  { text: "Voel je je rustig als alles om je heen stabiel is?", cat: "HARMONIE", value: "Veiligheid" },
  { text: "Kun je schoonheid zien in alledaagse dingen?", cat: "HARMONIE", value: "Schoonheid" },
  { text: "Is je huis een rustpunt voor je ziel?", cat: "HARMONIE", value: "Rust" },
  { text: "Geloof je dat alles met een reden gebeurt?", cat: "HARMONIE", value: "Hoop" },
  { text: "Ben je flexibel in je denken over goed en kwaad?", cat: "HARMONIE", value: "Flexibiliteit" },
  { text: "Geef je meer aan anderen dan je voor jezelf houdt?", cat: "HARMONIE", value: "Vrijgevigheid" },
  { text: "Houd je van de sfeer van oude tradities?", cat: "HARMONIE", value: "Traditie" },
  { text: "Ben je bereid te vechten voor de veiligheid van je gezin?", cat: "HARMONIE", value: "Beschermen" },
  { text: "Is innerlijke vrede je ultieme doel?", cat: "HARMONIE", value: "Tevredenheid" },

  // --- CATEGORIE: DYNAMIEK ---
  { text: "Heb je elke week behoefte aan een nieuwe omgeving?", cat: "DYNAMIEK", value: "Afwisseling" },
  { text: "Zou je het liefst morgen vertrekken naar een onbekende plek?", cat: "DYNAMIEK", value: "Avontuurlijkheid" },
  { text: "Is het voor jou belangrijk dat jouw naam bij een succes staat?", cat: "DYNAMIEK", value: "Erkenning" },
  { text: "Gaat de loyaliteit naar je gezin boven alles?", cat: "DYNAMIEK", value: "Familie" },
  { text: "Blijf je bij je principes, ook als dat je je baan kan kosten?", cat: "DYNAMIEK", value: "Integriteit" },
  { text: "Doe je dingen graag op een manier die nog nooit geprobeerd is?", cat: "DYNAMIEK", value: "Originaliteit" },
  { text: "Heb je af en toe een adrenalinekick nodig?", cat: "DYNAMIEK", value: "Spanning" },
  { text: "Geloof je dat er een hogere macht of energie is?", cat: "DYNAMIEK", value: "Spiritualiteit" },
  { text: "Zoek je taken op die net boven je niveau liggen?", cat: "DYNAMIEK", value: "Uitdaging" },
  { text: "Is het voor jou onverdraaglijk als iemand je regels oplegt?", cat: "DYNAMIEK", value: "Vrijheid" },
  { text: "Ben je een pionier die graag nieuwe paden bewandelt?", cat: "DYNAMIEK", value: "Innovatief" },
  { text: "Wil je opvallen door je kleding of unieke levensstijl?", cat: "DYNAMIEK", value: "Originaliteit" },
  { text: "Voel je je snel opgesloten in een standaard kantooromgeving?", cat: "DYNAMIEK", value: "Vrijheid" },
  { text: "Is je familie het middelpunt van al je beslissingen?", cat: "DYNAMIEK", value: "Familie" },
  { text: "Mediteer je of bid je om contact te maken met het universum?", cat: "DYNAMIEK", value: "Spiritualiteit" },
  { text: "Heb je een hekel aan sleur en routine?", cat: "DYNAMIEK", value: "Afwisseling" },
  { text: "Neem je vaak risico's om iets groots te bereiken?", cat: "DYNAMIEK", value: "Spanning" },
  { text: "Wil je dat mensen je bewonderen om je unieke prestaties?", cat: "DYNAMIEK", value: "Erkenning" },
  { text: "Handel je altijd volgens je innerlijke morele kompas?", cat: "DYNAMIEK", value: "Integriteit" },
  { text: "Ben je bereid te breken met het verleden voor een nieuwe start?", cat: "DYNAMIEK", value: "Uitdaging" },
  { text: "Is vrijheid van meningsuiting je meest dierbare recht?", cat: "DYNAMIEK", value: "Vrijheid" },
  { text: "Ben je bereid te verhuizen voor een geweldig avontuur?", cat: "DYNAMIEK", value: "Avontuurlijkheid" },
  { text: "Is je familieband belangrijker dan je carrière?", cat: "DYNAMIEK", value: "Familie" },
  { text: "Experimenteer je graag met onbewezen methodes?", cat: "DYNAMIEK", value: "Innovatief" },
  { text: "Voel je je aangetrokken tot het mystieke of onverklaarbare?", cat: "DYNAMIEK", value: "Spiritualiteit" },
  { text: "Verander je vaak je interieur of uiterlijk voor de variatie?", cat: "DYNAMIEK", value: "Afwisseling" },
  { text: "Zoek je competitie op om jezelf te testen?", cat: "DYNAMIEK", value: "Uitdaging" },
  { text: "Ben je trots op je eigenzinnigheid?", cat: "DYNAMIEK", value: "Originaliteit" },
  { text: "Is jouw integriteit niet te koop, voor geen enkel bedrag?", cat: "DYNAMIEK", value: "Integriteit" },
  { text: "Houd je van sporten waarbij snelheid of risico een rol speelt?", cat: "DYNAMIEK", value: "Spanning" },
  { text: "Heb je een sterke drang naar onafhankelijkheid?", cat: "DYNAMIEK", value: "Vrijheid" },
  { text: "Ben je een ontdekkingsreiziger in je eigen stad?", cat: "DYNAMIEK", value: "Avontuurlijkheid" },
  { text: "Is de goedkeuring van je ouders of kinderen erg belangrijk?", cat: "DYNAMIEK", value: "Familie" },
  { text: "Bedenk je vaak producten die nog niet bestaan?", cat: "DYNAMIEK", value: "Innovatief" },
  { text: "Voel je je verbonden met een groter kosmisch plan?", cat: "DYNAMIEK", value: "Spiritualiteit" },
  { text: "Kan je goed omgaan met onzekerheid over de toekomst?", cat: "DYNAMIEK", value: "Spanning" },
  { text: "Wil je herinnerd worden als iemand die 'anders' was?", cat: "DYNAMIEK", value: "Originaliteit" },
  { text: "Is eerlijkheid naar jezelf toe je zwaarste taak?", cat: "DYNAMIEK", value: "Integriteit" },
  { text: "Verveel je je snel als alles volgens plan verloopt?", cat: "DYNAMIEK", value: "Afwisseling" },
  { text: "Is de weg naar het doel belangrijker dan het doel zelf?", cat: "DYNAMIEK", value: "Avontuurlijkheid" },
];